/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "passport.token": [],
    "passport.authorizations.authorize": [],
    "passport.token.refresh": [],
    "passport.authorizations.approve": [],
    "passport.authorizations.deny": [],
    "passport.tokens.index": [],
    "passport.tokens.destroy": [
        {
            "name": "token_id"
        }
    ],
    "passport.clients.index": [],
    "passport.clients.store": [],
    "passport.clients.update": [
        {
            "name": "client_id"
        }
    ],
    "passport.clients.destroy": [
        {
            "name": "client_id"
        }
    ],
    "passport.scopes.index": [],
    "passport.personal.tokens.index": [],
    "passport.personal.tokens.store": [],
    "passport.personal.tokens.destroy": [
        {
            "name": "token_id"
        }
    ],
    "sanctum.csrf-cookie": [],
    "ignition.healthCheck": [],
    "ignition.executeSolution": [],
    "ignition.updateConfig": [],
    "travels.raw-data": [],
    "travels.raw-data.download": [],
    "travels.distance": [],
    "travels.distance.download": [],
    "element-types.index": [],
    "element-types.store": [],
    "profile.edit": [],
    "profile.update": [],
    "profile.destroy": [],
    "register": [],
    "login": [],
    "password.request": [],
    "password.email": [],
    "password.reset": [
        {
            "name": "token"
        }
    ],
    "password.store": [],
    "verification.notice": [],
    "verification.verify": [
        {
            "name": "id"
        },
        {
            "name": "hash"
        }
    ],
    "verification.send": [],
    "password.confirm": [],
    "password.update": [],
    "logout": []
}
}
export {};
