version: "3.7"
services:
    carnaval-api:
        build:
            args:
                user: carnaval
                uid: 1000
            context: .
            dockerfile: Dockerfile
        image: carnaval-image
        container_name: carnaval-api
        restart: unless-stopped
        tty: true
        working_dir: /var/www/
        volumes:
            - ./:/var/www
            - ./docker/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
        networks:
            - carnaval

    carnaval-db:
        image: mysql:latest
        platform: linux/amd64
        container_name: carnaval-db
        restart: unless-stopped
        tty: true
        volumes:
            - ./mysql-files:/var/lib/mysql-files
            - dbdata:/var/lib/mysql
            - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        ports:
            - 3308:3306
        networks:
            - carnaval

    carnaval-nginx:
        image: nginx:1.17-alpine
        container_name: carnaval-nginx
        restart: unless-stopped
        tty: true
        depends_on:
            - carnaval-api
            - carnaval-db
        ports:
            - 8008:80
        volumes:
            - ./:/var/www
            - ./docker/nginx:/etc/nginx/conf.d
        networks:
            - carnaval

volumes:
    dbdata:
networks:
    carnaval:
        driver: bridge
